### ISSUE TITLE
Fail to install with opam

### ISSUE THREAD

**Issue by Naereen** [akabe/ocaml-jupyter#52]
Apparently, the installation script tries to install the kernel to `/usr/share/jupyter/kernels/`, which would require root rights, but I am unable to either launch `opam install jupter` with the good options or with `sudo`.

The error is:
```bash
[Errno 13] Permission denied: '/usr/local/share/jupyter/kernels/ocaml-jupyter-4.04.2'
Perhaps you want to install with `sudo` or `--user`?
E: Failure("Command './kernelspec.sh install true /home/lilian/.opam/4.04.2/share/ocaml-jupyter' terminated with error code 1")
```

I tried to manually hack the `kernelspec.sh` script to force using `sudo jupyter ...` and reinstalling from local archive (manually modified), but this is not working.

Any insights? Any easy way of fixing that?
Thanks!

PS: it could help to also provide instructions on how to compile and install from the git repository.

**Comment by akabe** [comment]
What's the version  of ocaml-jupyter? Can `opam update && opam upgrade` fix it?

**Comment by Naereen** [comment]
I was using the `0.1.0` version.

Sorry, my setup works like this and everytime I `opam upgrade`, something gets broken...

**Comment by akabe** [comment]
I fixed the bug at v1.0.1: https://github.com/akabe/ocaml-jupyter/pull/44

I agree that `opam upgrade` sometimes fails. Maybe I can solve the problem if you show me output log of `opam upgrade`.

**Comment by Naereen** [comment]
OK good. It is working for me since the manual install, and I don't have time right now to try again but I believe it is fixed.
Will try on another laptop asap.

**Comment by jotterbach** [comment]
Hi @akabe 
I'm running into the same issue, when running the `opam install` command within a Docker build. The stack trace is:

```
Step 7/9 : RUN opam install -y jupyter
 ---> Running in d83f5d46545d
[WARNING] Running as root is not recommended
The following actions will be performed:
  - install   uuidm               0.9.6                         [required by jupyter]
  - install   base64              2.2.0                         [required by jupyter]
  - install   conf-gmp            1                             [required by zarith]
  - install   mirage-no-solo5     1                             [required by nocrypto]
  - install   conf-zmq            0.1                           [required by zmq]
  - install   conf-perl           1                             [required by zarith]
  - install   ocb-stubblr         0.1.1                         [required by nocrypto]
  - upgrade   cppo                1.4.1 to 1.6.0                [required by jupyter]
  - install   stdint              0.4.2                         [required by zmq]
  - install   mirage-no-xen       1                             [required by nocrypto]
  - install   zarith              1.5                           [required by nocrypto]
  - install   cpuid               0.1.1                         [required by nocrypto]
  - install   ocplib-endian       1.0                           [required by cstruct]
  - install   cppo_ocamlbuild     1.6.0                         [required by jupyter]
  - recompile utop                1.19.3                        [uses cppo]
  - install   zmq                 4.0-8                         [required by jupyter]
  - install   cstruct             3.1.1                         [required by nocrypto]
  - install   ppx_deriving        4.1                           [required by nocrypto, ppx_deriving_yojson]
  - install   lwt-zmq             2.1.0                         [required by jupyter]
  - install   cstruct-lwt         3.1.1                         [required by nocrypto]
  - install   ppx_deriving_yojson 3.0                           [required by jupyter]
  - recompile ppx_type_conv       v0.9.0                        [uses ppx_deriving]
  - recompile ppx_variants_conv   v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_typerep_conv    v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_traverse        v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_sexp_conv       v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_fields_conv     v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_enumerate       v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_compare         v0.9.0                        [uses ppx_type_conv]
  - install   nocrypto            0.5.4                         [required by jupyter]
  - recompile ppx_sexp_value      v0.9.0                        [uses ppx_sexp_conv]
  - recompile ppx_sexp_message    v0.9.0                        [uses ppx_sexp_conv]
  - recompile ppx_custom_printf   v0.9.0                        [uses ppx_sexp_conv, ppx_traverse]
  - recompile ppx_hash            v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_assert          v0.9.0                        [uses ppx_type_conv]
  - install   jupyter             0.1.0
  - recompile bin_prot            v0.9.1                        [uses ppx_sexp_conv, ppx_compare, ppx_fields_conv, ppx_variants_conv]
  - recompile ppx_base            v0.9.0                        [uses ppx_type_conv]
  - recompile ppx_expect          v0.9.0                        [uses ppx_traverse, ppx_fields_conv, ppx_assert, etc.]
  - recompile ppx_bin_prot        v0.9.0                        [uses ppx_type_conv]
  - recompile configurator        v0.9.1                        [uses ppx_base]
  - recompile ppx_jane            v0.9.0                        [uses ppx_typerep_conv, ppx_bin_prot, ppx_assert, etc.]
  - recompile core_kernel         v0.9.0                        [uses ppx_base, ppx_assert, ppx_sexp_conv]
  - recompile re2                 v0.9.0                        [uses core_kernel]
  - recompile core                v0.9.1                        [uses ppx_assert]
  - recompile textutils           v0.9.0                        [uses core]
  - recompile core_extended       v0.9.0                        [uses core_kernel, core, bin_prot]
===== 21 to install | 25 to recompile | 1 to upgrade =====

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[base64: from default] Command started
[bin_prot] Archive in cache
[configurator] Archive in cache
[core] Archive in cache
[core_extended] Archive in cache
[core_kernel] Archive in cache
[cppo: from default] Command started
[cppo_ocamlbuild: from default] Command started
[base64: from default] Command started
[default] https://opam.ocaml.org/archives/base64.2.2.0+opam.tar.gz downloaded
[cpuid: from default] Command started
[cppo_ocamlbuild: from default] Command started
[cppo: from default] Command started
[default] https://opam.ocaml.org/archives/cppo_ocamlbuild.1.6.0+opam.tar.gz downloaded
[cstruct: from default] Command started
[default] https://opam.ocaml.org/archives/cppo.1.6.0+opam.tar.gz downloaded
[cstruct-lwt: from default] Command started
[cpuid: from default] Command started
[default] https://opam.ocaml.org/archives/cpuid.0.1.1+opam.tar.gz downloaded
[jupyter: from default] Command started
[cstruct-lwt: from default] Command started
[default] https://opam.ocaml.org/archives/cstruct-lwt.3.1.1+opam.tar.gz downloaded
[lwt-zmq: from default] Command started
[jupyter: from default] Command started
[default] https://opam.ocaml.org/archives/jupyter.0.1.0+opam.tar.gz downloaded
[nocrypto: from default] Command started
[cstruct: from default] Command started
[default] https://opam.ocaml.org/archives/cstruct.3.1.1+opam.tar.gz downloaded
[ocb-stubblr: from default] Command started
[ocb-stubblr: from default] Command started
[lwt-zmq: from default] Command started
[default] https://opam.ocaml.org/archives/ocb-stubblr.0.1.1+opam.tar.gz downloaded
[ocplib-endian: from default] Command started
[default] https://opam.ocaml.org/archives/lwt-zmq.2.1.0+opam.tar.gz downloaded
[ppx_assert] Archive in cache
[ppx_base] Archive in cache
[ppx_bin_prot] Archive in cache
[ppx_compare] Archive in cache
[ppx_custom_printf] Archive in cache
[ppx_deriving: from default] Command started
[ppx_deriving: from default] Command started
[default] https://opam.ocaml.org/archives/ppx_deriving.4.1+opam.tar.gz downloaded
[ppx_deriving_yojson: from default] Command started
[ocplib-endian: from default] Command started
[default] https://opam.ocaml.org/archives/ocplib-endian.1.0+opam.tar.gz downloaded
[ppx_enumerate] Archive in cache
[ppx_expect] Archive in cache
[ppx_fields_conv] Archive in cache
[ppx_hash] Archive in cache
[ppx_jane] Archive in cache
[ppx_sexp_conv] Archive in cache
[ppx_sexp_message] Archive in cache
[ppx_sexp_value] Archive in cache
[ppx_traverse] Archive in cache
[ppx_type_conv] Archive in cache
[ppx_typerep_conv] Archive in cache
[ppx_variants_conv] Archive in cache
[re2] Archive in cache
[stdint: from default] Command started
[ppx_deriving_yojson: from default] Command started
[default] https://opam.ocaml.org/archives/ppx_deriving_yojson.3.0+opam.tar.gz downloaded
[textutils] Archive in cache
[utop] Archive in cache
[uuidm: from default] Command started
[stdint: from default] Command started
[default] https://opam.ocaml.org/archives/stdint.0.4.2+opam.tar.gz downloaded
[zarith: from default] Command started
[uuidm: from default] Command started
[default] https://opam.ocaml.org/archives/uuidm.0.9.6+opam.tar.gz downloaded
[zmq: from default] Command started
[zarith: from default] Command started
[default] https://opam.ocaml.org/archives/zarith.1.5+opam.tar.gz downloaded
[zmq: from default] Command started
[default] https://opam.ocaml.org/archives/zmq.4.0-8+opam.tar.gz downloaded
[nocrypto: from default] Command started
[default] https://opam.ocaml.org/archives/nocrypto.0.5.4+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
-> removed   core_extended.v0.9.0
-> removed   re2.v0.9.0
-> removed   textutils.v0.9.0
-> removed   core.v0.9.1
-> removed   core_kernel.v0.9.0
-> removed   configurator.v0.9.1
-> removed   ppx_jane.v0.9.0
-> removed   ppx_base.v0.9.0
-> removed   ppx_bin_prot.v0.9.0
-> removed   bin_prot.v0.9.1
-> removed   ppx_enumerate.v0.9.0
-> removed   ppx_expect.v0.9.0
-> removed   ppx_assert.v0.9.0
-> removed   ppx_custom_printf.v0.9.0
-> removed   ppx_fields_conv.v0.9.0
-> removed   ppx_hash.v0.9.0
-> removed   ppx_compare.v0.9.0
-> removed   ppx_sexp_message.v0.9.0
-> removed   ppx_sexp_value.v0.9.0
-> removed   ppx_sexp_conv.v0.9.0
-> removed   ppx_traverse.v0.9.0
-> removed   ppx_typerep_conv.v0.9.0
-> removed   ppx_variants_conv.v0.9.0
-> removed   ppx_type_conv.v0.9.0
[utop: ocamlfind remove] Command started
[base64: jbuilder build] Command started
[conf-gmp: sh] Command started
[conf-perl: perl] Command started
-> removed   utop.1.19.3
[cppo: ocamlfind remove] Command started
-> installed conf-perl.1
[conf-zmq: cc test.c] Command started
-> installed conf-gmp.1
-> installed mirage-no-solo5.1
-> installed mirage-no-xen.1
[ocb-stubblr: ocaml build] Command started
-> removed   cppo.1.4.1
[cppo: jbuilder build] Command started
-> installed base64.2.2.0
[stdint: ocaml setup.ml] Command started
-> installed conf-zmq.0.1
[uuidm: ocaml build] Command started
-> installed ocb-stubblr.0.1.1
[cpuid: ocaml build] Command started
-> installed cppo.1.6.0
[cppo_ocamlbuild: jbuilder build] Command started
-> installed uuidm.0.9.6
[ocplib-endian: ocaml setup.ml] Command started
-> installed cppo_ocamlbuild.1.6.0
[ppx_deriving: ocaml] Command started
[stdint: ocaml setup.ml] Command started
-> installed cpuid.0.1.1
[utop: ./configure] Command started
[ocplib-endian: ocaml setup.ml] Command started
[utop: make] Command started
[ocplib-endian: ocaml setup.ml] Command started
-> installed ocplib-endian.1.0
[cstruct: jbuilder build] Command started
-> installed cstruct.3.1.1
[cstruct-lwt: jbuilder build] Command started
-> installed cstruct-lwt.3.1.1
[zarith: ./configure] Command started
-> installed ppx_deriving.4.1
[ppx_deriving_yojson: ocaml] Command started
[zarith: make] Command started
[stdint: ocaml setup.ml] Command started
[utop: make install] Command started
-> installed utop.1.19.3
[ppx_type_conv: jbuilder build] Command started
-> installed ppx_deriving_yojson.3.0
[zarith: make install] Command started
-> installed zarith.1.5
-> installed stdint.0.4.2
[zmq: ocaml setup.ml] Command started
-> installed ppx_type_conv.v0.9.0
[ppx_compare: jbuilder build] Command started
[ppx_enumerate: jbuilder build] Command started
[ppx_fields_conv: jbuilder build] Command started
[zmq: ocaml setup.ml] Command started
-> installed ppx_enumerate.v0.9.0
[ppx_sexp_conv: jbuilder build] Command started
-> installed ppx_compare.v0.9.0
[ppx_traverse: jbuilder build] Command started
-> installed ppx_fields_conv.v0.9.0
[ppx_typerep_conv: jbuilder build] Command started
-> installed ppx_sexp_conv.v0.9.0
[nocrypto: ocaml build] Command started
-> installed ppx_typerep_conv.v0.9.0
[ppx_assert: jbuilder build] Command started
-> installed ppx_traverse.v0.9.0
[ppx_custom_printf: jbuilder build] Command started
-> installed ppx_assert.v0.9.0
[ppx_hash: jbuilder build] Command started
-> installed ppx_custom_printf.v0.9.0
[ppx_sexp_message: jbuilder build] Command started
[zmq: ocaml setup.ml] Command started
-> installed ppx_hash.v0.9.0
[ppx_base: jbuilder build] Command started
-> installed ppx_sexp_message.v0.9.0
[ppx_sexp_value: jbuilder build] Command started
-> installed zmq.4.0-8
[lwt-zmq: ocaml setup.ml] Command started
-> installed ppx_base.v0.9.0
[configurator: jbuilder build] Command started
[lwt-zmq: ocaml setup.ml] Command started
-> installed ppx_sexp_value.v0.9.0
[ppx_variants_conv: jbuilder build] Command started
-> installed configurator.v0.9.1
-> installed ppx_variants_conv.v0.9.0
[bin_prot: jbuilder build] Command started
[ppx_expect: jbuilder build] Command started
-> installed nocrypto.0.5.4
[lwt-zmq: ocaml setup.ml] Command started
-> installed bin_prot.v0.9.1
[ppx_bin_prot: jbuilder build] Command started
-> installed lwt-zmq.2.1.0
[jupyter: ocaml setup.ml] Command started
-> installed ppx_expect.v0.9.0
-> installed ppx_bin_prot.v0.9.0
[ppx_jane: jbuilder build] Command started
[jupyter: ocaml setup.ml] Command started
-> installed ppx_jane.v0.9.0
[core_kernel: jbuilder build] Command started
[ERROR] The compilation of jupyter failed at "ocaml setup.ml -build".
[jupyter: sh] Command started
[jupyter: rm] Command started
-> installed core_kernel.v0.9.0
[core: jbuilder build] Command started
[re2: jbuilder build] Command started
-> installed core.v0.9.1
[textutils: jbuilder build] Command started
-> installed textutils.v0.9.0
-> installed re2.v0.9.0
[core_extended: jbuilder build] Command started
-> installed core_extended.v0.9.0

#=== ERROR while installing jupyter.0.1.0 =====================================#
# opam-version         1.2.2
# os                   linux
# command              ocaml setup.ml -build
# path                 /root/.opam/4.04.0/build/jupyter.0.1.0
# compiler             4.04.0
# exit-code            1
# env-file             /root/.opam/4.04.0/build/jupyter.0.1.0/jupyter-5-672e8b.env
# stdout-file          /root/.opam/4.04.0/build/jupyter.0.1.0/jupyter-5-672e8b.out
# stderr-file          /root/.opam/4.04.0/build/jupyter.0.1.0/jupyter-5-672e8b.err
### stdout ###
# [...]
# /root/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -no-alias-deps -strict-formats -strict-sequence -I lib/core -I lib/repl -I lib/kernel -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58 -package yojson -package uuidm -package ppx_deriving_yojson -package nocrypto -package lwt.unix -package lwt.ppx -package lwt-zmq -package lwt -package compiler-libs.toplevel -package compiler-libs.common -I src -I lib/kernel -o src/JupyterMain.cmo src/JupyterMain.ml
# + /root/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -no-alias-deps -strict-formats -strict-sequence -I lib/core -I lib/repl -I lib/kernel -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58 -package yojson -package uuidm -package ppx_deriving_yojson -package nocrypto -package lwt.unix -package lwt.ppx -package lwt-zmq -package lwt -package compiler-libs.toplevel -package compiler-libs.common -I src -I lib/kernel -o src/JupyterMain.cmo src/JupyterMain.ml
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opam/4.04.0/lib/ocaml/compiler-libs, /root/.opam/4.04.0/lib/ocaml
# /root/.opam/4.04.0/bin/ocamlfind ocamldep -package yojson -package uuidm -package ppx_deriving_yojson -package nocrypto -package lwt.unix -package lwt.ppx -package lwt-zmq -package lwt -package compiler-libs.toplevel -package compiler-libs.common -modules src/JupyterArgs.ml > src/JupyterArgs.ml.depends
# /root/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -no-alias-deps -strict-formats -strict-sequence -I lib/core -I lib/repl -I lib/kernel -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58 -package yojson -package uuidm -package ppx_deriving_yojson -package nocrypto -package lwt.unix -package lwt.ppx -package lwt-zmq -package lwt -package compiler-libs.toplevel -package compiler-libs.common -I src -I lib/kernel -o src/JupyterArgs.cmo src/JupyterArgs.ml
# + /root/.opam/4.04.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -no-alias-deps -strict-formats -strict-sequence -I lib/core -I lib/repl -I lib/kernel -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58 -package yojson -package uuidm -package ppx_deriving_yojson -package nocrypto -package lwt.unix -package lwt.ppx -package lwt-zmq -package lwt -package compiler-libs.toplevel -package compiler-libs.common -I src -I lib/kernel -o src/JupyterArgs.cmo src/JupyterArgs.ml
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opam/4.04.0/lib/ocaml/compiler-libs, /root/.opam/4.04.0/lib/ocaml
# File "src/JupyterArgs.ml", line 36, characters 8-31:
# Error: Unbound value Lwt_log.level_of_string
# Command exited with code 2.
### stderr ###
# W: Cannot find source file matching module 'JupyterReplToploop' in library jupyter-repl.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# W: Cannot find source file matching module 'JupyterReplError' in library jupyter-repl.
# W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
# E: Failure("Command ''/root/.opam/4.04.0/bin/ocamlbuild' lib/core/jupyter.cma lib/core/jupyter.cmxa lib/core/jupyter.a lib/core/jupyter.cmxs lib/repl/jupyter-repl.cma lib/kernel/jupyter-kernel.cma lib/kernel/jupyter-kernel.cmxa lib/kernel/jupyter-kernel.a lib/kernel/jupyter-kernel.cmxs src/JupyterMain.byte lib/notebook/jupyter-notebook.cma lib/notebook/jupyter-notebook.cmxa lib/notebook/jupyter-notebook.a lib/notebook/jupyter-notebook.cmxs -use-ocamlfind -plugin-tags 'package(cppo_ocamlbuild)' -tag debug' terminated with error code 10")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install jupyter 0.1.0
The following changes have been performed
  - install base64              2.2.0
  - install conf-gmp            1
  - install conf-perl           1
  - install conf-zmq            0.1
  - upgrade cppo                1.4.1 to 1.6.0
  - install cppo_ocamlbuild     1.6.0
  - install cpuid               0.1.1
  - install cstruct             3.1.1
  - install cstruct-lwt         3.1.1
  - install lwt-zmq             2.1.0
  - install mirage-no-solo5     1
  - install mirage-no-xen       1
  - install nocrypto            0.5.4
  - install ocb-stubblr         0.1.1
  - install ocplib-endian       1.0
  - install ppx_deriving        4.1
  - install ppx_deriving_yojson 3.0
  - install stdint              0.4.2
  - install uuidm               0.9.6
  - install zarith              1.5
  - install zmq                 4.0-8

=-=- jupyter.0.1.0 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> If Jupyter is installed, ocaml-jupyter kernel is already available.
=> Otherwise you setup Jupyter and the OCaml kernel as follows:
=>
=> $ pip install jupyter
=> $ jupyter kernelspec install --name ocaml-jupyter-4.04.0 \
       /root/.opam/4.04.0/share/ocaml-jupyter

The former state can be restored with:
    opam switch import "~/.opam/4.04.0/backup/state-20170815052035.export"
The command '/bin/sh -c opam install -y jupyter' returned a non-zero code: 4
```

Any advice?

**Comment by akabe** [comment]
@jotterbach Please try `opam update`. The v0.1.0 has a bug maybe.

**Comment by akabe** [comment]
Maybe you are interested in https://github.com/akabe/docker-ocaml-jupyter-datascience

**Comment by jotterbach** [comment]
@akabe Thanks for the fast reply! I tried it with running `opam update` prior to installing ocaml-jupyter, but still getting the same error:

```
[ppx_jane: jbuilder build] Command started
-> installed ppx_jane.v0.9.0
[core_kernel: jbuilder build] Command started
-> installed zmq.4.0-8
[lwt-zmq: ocaml setup.ml] Command started
[lwt-zmq: ocaml setup.ml] Command started
[lwt-zmq: ocaml setup.ml] Command started
-> installed lwt-zmq.2.1.0
[jupyter: ocaml setup.ml] Command started
[jupyter: ocaml setup.ml] Command started
[jupyter: ocaml setup.ml] Command started
[ERROR] The compilation of jupyter failed at "ocaml setup.ml -install".
[jupyter: sh] Command started
[jupyter: rm] Command started
[WARNING] Directory /root/.opam/4.04.0/lib/jupyter is not empty, not removing
-> installed core_kernel.v0.9.0
[core: jbuilder build] Command started
[re2: jbuilder build] Command started
-> installed core.v0.9.1
[textutils: jbuilder build] Command started
-> installed textutils.v0.9.0
-> installed re2.v0.9.0
[core_extended: jbuilder build] Command started
-> installed core_extended.v0.9.0

#=== ERROR while installing jupyter.1.0.1 =====================================#
# opam-version         1.2.2
# os                   linux
# command              ocaml setup.ml -install
# path                 /root/.opam/4.04.0/build/jupyter.1.0.1
# compiler             4.04.0
# exit-code            1
# env-file             /root/.opam/4.04.0/build/jupyter.1.0.1/jupyter-6-4b889b.env
# stdout-file          /root/.opam/4.04.0/build/jupyter.1.0.1/jupyter-6-4b889b.out
# stderr-file          /root/.opam/4.04.0/build/jupyter.1.0.1/jupyter-6-4b889b.err
### stderr ###
# [...]
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebook.annot
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebookUnsafe.cmx
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebookStdin.cmx
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebookRouter.cmx
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebookCommManager.cmx
# Installed /root/.opam/4.04.0/lib/jupyter/JupyterNotebook.cmx
# Installed /root/.opam/4.04.0/lib/jupyter/META
# [WARNING] Running as root is not recommended
# ./kernelspec.sh: line 56: sudo: command not found
# E: Failure("Command './kernelspec.sh install true /root/.opam/4.04.0/share/ocaml-jupyter' terminated with error code 127")



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  - install jupyter 1.0.1
The following changes have been performed
  - install base64              2.2.0
  - install conf-gmp            1
  - install conf-gmp-powm-sec   1
  - install conf-perl           1
  - install conf-zlib           1
  - install conf-zmq            0.1
  - install cppo_ocamlbuild     1.6.0
  - install cryptokit           1.12
  - install lwt-zmq             2.1.0
  - install ppx_derivers        1.0
  - install ppx_deriving        4.2
  - install ppx_deriving_yojson 3.0
  - install stdint              0.3.0-0
  - install uuidm               0.9.6
  - install zarith              1.5
  - install zmq                 4.0-8

=-=- jupyter.1.0.1 troubleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> If Jupyter is installed, ocaml-jupyter kernel is already available.
=> Otherwise you setup Jupyter and the OCaml kernel as follows:
=>
=> $ pip install jupyter

The former state can be restored with:
    opam switch import "~/.opam/4.04.0/backup/state-20170815053719.export"
The command '/bin/sh -c opam install -y jupyter' returned a non-zero code: 4
```
The version is now updated, but still can't install. I would be interested in just using one of the pre-built versions but I need an image that contains the `dev` branch of Owl and hence I use that base container at the moment.

**Comment by akabe** [comment]
@jotterbach I see. The kernespec installer does not support execution on root without `sudo` since opam does not recommend to run on root. I'll fix the bug of the installer at the next release. If you want to immediately use the kernel, you can install it on a normal user or install `sudo`.

**Comment by akabe** [comment]
@jotterbach  Strange. I cannot reproduce your error. I tried this Dockerfile:

```
FROM centos:7

ENV OPAM_VERSION  1.2.2
ENV OCAML_VERSION 4.04.2

RUN yum update -y && \
    yum install -y sudo patch unzip make gcc && \
    curl -L -o /usr/bin/opam "https://github.com/ocaml/opam/releases/download/$OPAM_VERSION/opam-$OPAM_VERSION-$(uname -m)-$(uname -s)" && \
    chmod 755 /usr/bin/opam && \
    opam init -a -y --comp $OCAML_VERSION

RUN yum install -y epel-release && \
    yum install -y python34-devel python34-pip && \
    pip3 install --upgrade pip && \
    pip3 install --user --no-cache-dir 'setuptools>=18.5' 'six>=1.9.0' jupyter

RUN yum install -y which m4 rsync perl zlib-devel gcc zeromq-devel libffi-devel gmp-devel
RUN opam update
RUN opam upgrade -y

RUN yum remove -y sudo

RUN opam install -y jupyter
```

This successfully install the OCaml kernel.

**Comment by arshad01** [comment]
On my system (macOS 10.12.6 with ocaml 4.05.0) I get following error when I do opam install jupyter. Seems like some deps are not available for 4.05.0. 

```$ opam install jupyter
The following dependencies couldn't be met:
  - jupyter -> ppx_deriving_yojson >= 3.0 -> ppx_deriving < 3.0
Your request can't be satisfied:
  - ppx_deriving<1.0 is not available because your system doesn't comply with ocaml-version >= "4.02.0" & ocaml-version < "4.03".
  - ppx_deriving<2.0 is not available because your system doesn't comply with ocaml-version = "4.02.1" & ocaml-version < "4.03" & opam-version >= "1.2".
  - ppx_deriving<3.0 is not available because your system doesn't comply with ocaml-version >= "4.02.2" & ocaml-version < "4.03" & opam-version >= "1.2".
  - ppx_deriving_yojson>=3.0 is not available because your system doesn't comply with ocaml-version < "4.05.0".

No solution found, exiting```

**Comment by akabe** [comment]
@arshad01 Yes. ocaml-jupyter cannot be installed in 4.05 since `ppx_deriving_yojson` doesn't support the version: https://opam.ocaml.org/packages/ppx_deriving_yojson/ppx_deriving_yojson.3.0/
ocaml-jupyter itself does not directly depend on functionality of 4.05. If `ppx_deriving_yojson` will support 4.05, ocaml-jupyter will also without any change of code.
However I don't know when the restriction will be removed. If you don't have a reason you must use 4.05, please use 4.04.

**Comment by arshad01** [comment]
@akabe yes it installs successfully with 4.04. Thanks

**Comment by Naereen** [comment]
@akabe Shouldn't the README for ocaml-jupyter explicitly say that v4.05+ is not supported (yet) ?

**Comment by akabe** [comment]
@Naereen I disagree. I think the error message of opam is not so complex and

> ocaml-jupyter itself does not directly depend on functionality of 4.05. If ppx_deriving_yojson will support 4.05, ocaml-jupyter will also without any change of code.

I don't want to rewrite README depending on releasing of other packages.

**Comment by Naereen** [comment]
OK
